// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxBeHD5D85LZdLCtg6BmoJxkIOl3hE-U0',
    appId: '1:860812429904:web:efdf92455658b5a42e5f55',
    messagingSenderId: '860812429904',
    projectId: 'tutor-portal-d53d4',
    authDomain: 'tutor-portal-d53d4.firebaseapp.com',
    storageBucket: 'tutor-portal-d53d4.firebasestorage.app',
    measurementId: 'G-YQGB35QT58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkwHQZ_oRvUD3Jh1q5mq5XJ0ys_sg1zI',
    appId: '1:860812429904:android:f7d4c4d63270f6b82e5f55',
    messagingSenderId: '860812429904',
    projectId: 'tutor-portal-d53d4',
    storageBucket: 'tutor-portal-d53d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeRtUwQmKzq9LodTClYGQ7szeu38-w0Uc',
    appId: '1:860812429904:ios:df4877e5bf4794572e5f55',
    messagingSenderId: '860812429904',
    projectId: 'tutor-portal-d53d4',
    storageBucket: 'tutor-portal-d53d4.firebasestorage.app',
    iosBundleId: 'com.example.tutorPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeRtUwQmKzq9LodTClYGQ7szeu38-w0Uc',
    appId: '1:860812429904:ios:df4877e5bf4794572e5f55',
    messagingSenderId: '860812429904',
    projectId: 'tutor-portal-d53d4',
    storageBucket: 'tutor-portal-d53d4.firebasestorage.app',
    iosBundleId: 'com.example.tutorPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxBeHD5D85LZdLCtg6BmoJxkIOl3hE-U0',
    appId: '1:860812429904:web:53cc1d76543873932e5f55',
    messagingSenderId: '860812429904',
    projectId: 'tutor-portal-d53d4',
    authDomain: 'tutor-portal-d53d4.firebaseapp.com',
    storageBucket: 'tutor-portal-d53d4.firebasestorage.app',
    measurementId: 'G-P7ES0RSGXF',
  );
}
