import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  // Firebase must be ready before the first frame: ensureInitialized() binds the
  // engine so platform channels work, then initializeApp() loads the per-platform
  // options generated by `flutterfire configure` (lib/firebase_options.dart).
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: TutorPortalApp()));
}
